### ISSUE TITLE
Shall we use immutable mode?

### ISSUE THREAD

**Issue by robertbrook** [ukparliament/psephology-datasette#1]
https://docs.datasette.io/en/stable/performance.html#immutable-mode

**Comment by fantasticlife** [comment]
Tried that on an Heroku publish but no luck


datasette publish heroku -i psephology.db --metadata metadata.json -n psephology-datasette

Usage: datasette publish heroku [OPTIONS] [FILES]...

Try 'datasette publish heroku --help' for help.



Error: No such option: -i


From: Robert Brook ***@***.***>
Date: Tuesday, 21 May 2024 at 14:51
To: ukparliament/psephology-datasette ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ukparliament/psephology-datasette] Shall we use immutable mode? (Issue #1)

https://docs.datasette.io/en/stable/performance.html#immutable-mode
